# Generated by Django 4.0.5 on 2022-08-05 14:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sss', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Format doesn't match", regex='\\d{2}-\\d{7}-\\d')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_validity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, max_length=150, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('operations_manager', models.CharField(blank=True, default='Riku Dola', max_length=50)),
                ('validity', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_type', models.IntegerField(choices=[(1, 'Security Guard'), (2, 'Reliever Guard')], default=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('make', models.CharField(default='ARMSCOR', max_length=20)),
                ('kind', models.IntegerField(choices=[(1, 'Pistol'), (2, 'Shotgun')], default=1)),
                ('caliber', models.CharField(blank=True, default=' ', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('', ''), ('M', 'Male'), ('F', 'Female')], max_length=100, null=True)),
                ('residence_address', models.CharField(default='02 Javier St., Poblacion, San Juan, Batangas', max_length=150)),
                ('nbi_clearance_id', models.CharField(default='12345678901', max_length=21)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('highest_education', models.IntegerField(choices=[(1, 'College Graduate'), (2, 'College Undergraduate'), (3, 'High School Graduate')], default=1)),
                ('sss', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Format doesn't match", regex='\\d{2}-\\d{7}-\\d')])),
                ('agency_affiliation', models.DateField(null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guards', models.IntegerField(default=0)),
                ('designations', models.ManyToManyField(related_name='instructions', to='security.designation')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True, unique=True)),
                ('include', models.BooleanField(default=False)),
                ('contracts', models.ManyToManyField(blank=True, related_name='locations', to='security.contract')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('', ''), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_armed', models.BooleanField(default=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='security.location')),
                ('shifts', models.ManyToManyField(related_name='posts', through='security.Instruction', to='security.shift')),
            ],
        ),
        migrations.CreateModel(
            name='NBI',
            fields=[
                ('clearance_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='security.post'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='security.shift'),
        ),
        migrations.CreateModel(
            name='FirearmAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_list', to='security.ddo')),
                ('firearms', models.ManyToManyField(blank=True, related_name='assignments', to='security.firearm')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fa_list', to='security.post')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.contract')),
            ],
        ),
        migrations.AddField(
            model_name='designation',
            name='day_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.instruction'),
        ),
        migrations.AddField(
            model_name='designation',
            name='ddo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='security.ddo'),
        ),
        migrations.AddField(
            model_name='designation',
            name='guard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='security.guard'),
        ),
        migrations.AddField(
            model_name='ddo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ddos', to='security.location'),
        ),
        migrations.AddField(
            model_name='contract',
            name='nbi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='security.nbi'),
        ),
    ]
