# Generated by Django 4.0.5 on 2022-08-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_nbi_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
