# Generated by Django 4.0.5 on 2022-08-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_rename_nbi_clearance_id_nbi_clearance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbi',
            old_name='clearance_id',
            new_name='nbi_clearance_id',
        ),
    ]
