# Generated by Django 4.0.5 on 2022-08-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_rename_clearance_id_nbi_nbi_clearance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbi',
            name='nbi_clearance_id',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
