# Generated by Django 4.0.5 on 2022-08-06 06:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_alter_nbi_nbi_clearance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='contract',
            name='issued_date',
            field=models.DateField(default=datetime.date(2022, 8, 6)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
