# Generated by Django 4.0.5 on 2022-08-06 06:58

from django.db import migrations, models
import security.models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_alter_contract_options_contract_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='issued_date',
            field=models.DateField(default=security.models.start_time),
        ),
    ]
