# Generated by Django 4.0.5 on 2022-08-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_delete_license_guard_lesp_issued_date_delete_nbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='nbi_issued_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guard',
            name='nbi_clearance_id',
            field=models.CharField(max_length=21),
        ),
    ]
