# Generated by Django 4.0.5 on 2022-08-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_guard_nbi_issued_date_alter_guard_nbi_clearance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
