# Generated by Django 4.0.5 on 2022-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_customuser_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='daily_wage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
