# Generated by Django 4.0.5 on 2022-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_contract_daily_wage_alter_contract_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_wage', models.FloatField()),
            ],
        ),
    ]
