# Generated by Django 4.0.5 on 2022-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_jobrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
