# Generated by Django 4.0.5 on 2022-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_jobrequest_is_approved_jobrequest_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
