# Generated by Django 4.0.5 on 2022-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_jobrequest_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='daily_wage',
            field=models.FloatField(null=True),
        ),
    ]
