# Generated by Django 4.0.5 on 2022-08-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_alter_jobrequest_daily_wage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequest',
        ),
    ]
