# Generated by Django 4.0.5 on 2022-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
