# Generated by Django 4.0.5 on 2022-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0025_delete_jobrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending Request'), (2, 'Request Accepted'), (3, 'Proposal Approved')], default=1),
        ),
    ]
