# Generated by Django 4.0.5 on 2022-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0026_remove_contract_is_approved_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sss',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending Request'), (2, 'Contract Proposed'), (3, 'Proposal Approved')], default=1),
        ),
    ]
