# Generated by Django 4.1.5 on 2023-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0027_remove_customuser_sss_alter_contract_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgencyInformation",
        ),
    ]
